export interface Project {
  projectName: string;
  startDate: string | null;
  endDate: string | null;
  jobTitle: string;
  achievements: string[];
  technologies: string[];
  projectLinks: string[] | null;
  sourceCodeLink: string | null;
  location: string;
  domain: string;
  id: string;
}

export const workHistory: Record<string, Project[]> = {
  Avenga: [
    {
      id: 'erp',
      projectName: 'ERP system Rearchitecture',
      startDate: '2024-05-01',
      endDate: null,
      jobTitle: 'Front-end Developer',
      location: 'Warsaw, Poland (Remote)',
      achievements: [
        'Took Part in rearchitecture from vanilla JS to React of ERP system to collect and control flow (Parts, Orders, Contacts, Invoices, Fixtures etc) for assembling line.',
        "Made significant contributions to project's architecture and code style",
      ],
      technologies: [
        'React.js',
        'TypeScript',
        'Tanstack Query',
        'Tanstack Router',
        'Vitest',
        'Git',
      ],
      projectLinks: null,
      sourceCodeLink: null,
      domain: 'ERP',
    },
  ],
  'Techlexity [Part-time]': [
    {
      id: 'leadtower',
      projectName: 'Leadtower',
      startDate: '2024-04-01',
      endDate: '2024-06-01',
      jobTitle: 'Key FullStack Developer',
      location: 'Warsaw, Poland (Remote)',
      achievements: [
        'Developed Next JS website',
        'Optimized website SEO',
        'Managed backend using Airtable and Server Actions',
        'Developed managable blog using Airtable and Next JS Server Actions',
      ],
      technologies: [
        'Next.js',
        'React',
        'TypeScript',
        'Airtable',
        'TypeScript',
        'Chakra UI',
        'Git',
      ],
      projectLinks: ['https://www.leadtower.io/'],
      sourceCodeLink: null,
      domain: 'Automation',
    },
  ],
  EPAM: [
    {
      id: 'epam-birds',
      projectName: 'Birds for Children App',
      startDate: '2023-11-01',
      endDate: '2024-04-01',
      jobTitle: 'Key Front-end Developer',
      location: 'Warsaw, Poland (Remote)',
      achievements: [
        'Independently chose AWS Amplify strategy for the whole team',
        'Managed Amplify backend',
        'Mentored intern developers',
        'Managed CI/CD on AWS',
        "Made significant contributions to project's architecture and code style",
      ],
      technologies: [
        'Next.js',
        'React',
        'TypeScript',
        'AWS Amplify',
        'TypeScript',
        'Styled Components',
        'DynamoDB',
        'AWS console',
        'GraphQL',
        'Git',
        'CI/CD',
      ],
      projectLinks: null,
      sourceCodeLink: null,
      domain: 'Education',
    },
    {
      id: 'epam-ecommerce',
      projectName: 'Luxury Clothing Brand Redesign',
      startDate: '2023-04-01',
      endDate: '2023-11-01',
      jobTitle: 'Front-end Developer',
      location: 'Warsaw, Poland (Remote)',
      achievements: [
        'Redesigned luxury clothing brand website',
        'Developed micro front-end on React and NodeJS',
        'Provided pull request management and efficient code reviews',
        'Covered code with unit tests',
        'Helped QA team by writing Playwright tests',
        'Independently implemented complex UI/UX features',
      ],
      technologies: [
        'React',
        'TypeScript',
        'NodeJS',
        'New Relic',
        'TypeScript',
        'Redux',
        'Redux Saga',
        'Jest',
        'Playwright',
        'GraphQL',
        'Apollo Client',
      ],
      projectLinks: null,
      sourceCodeLink: null,
      domain: 'E-commerce',
    },
    {
      id: 'epam-business-model',
      projectName: 'Business Model Integration',
      startDate: '2022-04-01',
      endDate: '2023-04-01',
      jobTitle: 'Front-end Developer',
      location: 'Warsaw, Poland (Remote)',
      achievements: [
        'Implemented front-end part of the project using React',
        'Wrote unit tests with 80% coverage',
        'Implemented SSO Authentication',
        'Migrated framework from Webpack to Vite',
      ],
      technologies: ['React', 'Git', 'Vite', 'SSO Authentication', 'REST API'],
      projectLinks: null,
      sourceCodeLink: null,
      domain: 'Fintech',
    },
  ],
  Techlexity: [
    {
      id: 'compassly',
      projectName: 'Compassly',
      startDate: '2021-10-01',
      endDate: '2022-05-01',
      jobTitle: 'Key React Native Developer',
      location: 'Ukraine, Lviv',
      achievements: [
        'Developed React Native app for iOS and Android',
        'Developed Custom Interactive Charts',
        'Implemented OAuth',
        'Chose project architecture',
        'Implemented Push Notifications',
      ],
      technologies: [
        'React Native',
        'TypeScript',
        'React Native CLI',
        'Biometric Auth',
        'Redux',
        'Async Storage',
        'Redux toolkit',
        'Redux thunk',
      ],
      projectLinks: [
        'https://play.google.com/store/apps/details?id=com.compassly&hl=uk',
        'https://apps.apple.com/pl/app/compassly/id1585777645',
      ],
      sourceCodeLink: null,
      domain: 'Medical',
    },
    {
      id: 'restaurant-app',
      projectName: 'Restaruant Booking App',
      startDate: '2021-10-01',
      endDate: '2022-05-01',
      jobTitle: 'Key React Native Developer',
      location: 'Ukraine, Lviv',
      achievements: [
        'Developed React Native app for iOS and Android',
        'Implemented Google and IOS Maps',
        'Implemented RealTime Chat',
        'Implemented Push Notifications',
        'Implemented Jwt Authentication',
        'Implemented Firebase Cloud Messaging',
        'Implemented Map Clustering for huge amount of markers',
      ],
      technologies: [
        'React Native',
        'TypeScript',
        'React Native CLI',
        'Biometric Auth',
        'Redux',
        'Async Storage',
        'Redux toolkit',
        'Redux thunk',
        'IOS Maps',
        'Google Maps',
        'Google Cloud Console',
        'Firebase',
        'WebSockets',
      ],
      projectLinks: [
        'https://play.google.com/store/apps/details?id=com.compassly&hl=uk',
        'https://apps.apple.com/pl/app/compassly/id1585777645',
      ],
      sourceCodeLink: null,
      domain: 'Entertainment',
    },
    {
      id: 'testigram',
      projectName: 'Testigram',
      endDate: '2021-10-01',
      startDate: '2021-05-01',
      jobTitle: 'Key Front-end Developer',
      location: 'Ukraine, Lviv',
      achievements: [
        'Developed reusable components',
        'Implemented virtualized list and customizable profile photo selection',
        'Created admin panel with word blacklist and data management',
      ],
      technologies: [
        'React',
        'JavaScript',
        'TypeScript',
        'Redux Toolkit',
        'Redux',
        'HTML5',
        'SCSS',
        'SCRUM',
        'Git',
      ],
      projectLinks: ['https://www.testigram.ai/'],
      sourceCodeLink: null,
      domain: 'Social Network',
    },
  ],
  'Freelance 2020': [
    {
      id: 'freelance-2020',
      projectName: 'Responsive Layout Development',
      startDate: '2020-06-01',
      endDate: '2020-11-01',
      jobTitle: 'HTML5 JS Developer',
      location: 'Remote',
      achievements: [
        'Developed responsive layouts with pixel-perfect design',
        'Implemented interactive animations using JQuery and SCSS',
      ],
      technologies: ['SASS', 'JavaScript', 'HTML', 'Pixel Perfect', 'Jquery'],
      projectLinks: null,
      sourceCodeLink: null,
      domain: 'Web Design',
    },
  ],
  'Other Projects': [
    {
      id: 'staking-app',
      projectName: 'Crypto Staking App',
      startDate: null,
      endDate: null,
      jobTitle: 'Fullstack Developer',
      location: 'Warsaw, Poland (Remote)',
      achievements: [
        'Created responsive UI with React and Shadcn UI',
        'Created admin panel using React-Admin',
        'Implemented authentication with JWT',
        'Implemented CRUD operations with Express JS and Drizzle ORM',
      ],
      technologies: [
        'postgreSQL',
        'TypeScript',
        'Drizzle ORM',
        'Express JS',
        'Git',
        'Git actions',
        'React',
        'TypeScript',
        'Tanstack Query',
        'React',
        'Zustand',
        'Axios',
        'react-admin',
      ],
      projectLinks: null,
      sourceCodeLink: null,
      domain: 'Web3',
    },
    {
      id: 'vidbil-bot',
      projectName: 'Telegram Bot with Admin Panel',
      startDate: null,
      endDate: null,
      jobTitle: 'Bot Developer',
      location: 'Warsaw, Poland (Remote)',
      achievements: [
        'Developed multifunctional bot with document verification and shopping features',
        'Migrated CI/CD to DigitalOcean',
        'Launched bot on Telegram',
        'Created admin panel for user management',
      ],
      technologies: [
        'Node.js',
        'TypeScript',
        'Mongoose',
        'telegram-bot-api',
        'Git',
        'Git actions',
        'MongoDB',
        'Express JS',
        'REST API',
        'React',
        'Redux',
        'Axios',
      ],
      projectLinks: ['https://t.me/Vidbilbot'],
      sourceCodeLink: null,
      domain: 'Medicine',
    },
  ],
};

export const allProjects: Project[] = Object.values(workHistory).flat();
